services:
  shared_database:
    image: postgres:14.22-trixie
    restart: always
    ports:
      - "5435:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./shared/scripts:/docker-entrypoint-initdb.d/

volumes:
  postgres_data: