spring.application.name=product.service

# server details
server.port=8081

# database properties
spring.datasource.username=admin
spring.datasource.password=admin
spring.datasource.url=jdbc:postgresql://localhost:5435/product_service
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update