spring.application.name=product.service

# server details
server.port=8081

# database properties
spring.datasource.username=admin
spring.datasource.password=admin
spring.datasource.url=jdbc:postgresql://localhost:5435/product_service?options=-c%20TimeZone=Asia/Kolkata
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# RabbitMQ properties
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=admin
spring.rabbitmq.password=admin